name: Release

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npx ci
    - name: Install sematic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint-fix
    - name: Test
      run: npm run test:unit-coverage --if-present
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release